# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
np.show_config()

2.4.6
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-58rizu_g/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-58rizu_g/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.31.188.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      SkylakeX MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.31.188.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-58rizu_g/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-58rizu_g/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null_arr = np.empty(10)
print(null_arr)

[nan  0.  0.  0.  0.  0.  0.  0.  0.  0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
null_arr.size

10

In [7]:
nz=np.array([1, 0, 3, 0, 0, 4])
nz.nbytes

48

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [4]:
!python -c "import numpy; numpy.info(numpy.add)"
#np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
nv = np.zeros(10)
nv[4] = 1
nv

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
np.arange(10, 49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [47]:
arr[::-1]     # Starts from beggining, stpes of -1

array([23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [48]:
np.flip(arr)

array([23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [66]:
#np.ceil(np.random.random((3, 3))*8)
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [73]:
arr = np.array([1,2,0,0,4,0])
arr.nonzero()

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [104]:
np.random.random((3, 3, 3))

array([[[0.35958219, 0.75733476, 0.2640631 ],
        [0.08434672, 0.25781561, 0.45011209],
        [0.01354483, 0.88436144, 0.40725941]],

       [[0.17301314, 0.29326257, 0.95095673],
        [0.66451746, 0.97109279, 0.38657967],
        [0.19871727, 0.07527076, 0.37061507]],

       [[0.10713345, 0.72692677, 0.04582858],
        [0.03529194, 0.18008669, 0.31471977],
        [0.23352994, 0.99258865, 0.25666357]]])

In [102]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [109]:
arr = np.random.random((10, 10))
print(arr)
minv, maxv = arr.min(), arr.max()
print(minv, maxv)

[[0.72580637 0.06741707 0.97877762 0.48071274 0.37944702 0.43615635
  0.21907557 0.11954677 0.32676081 0.63901603]
 [0.56818706 0.63642941 0.29394024 0.19025033 0.53879912 0.72988795
  0.01646605 0.22157187 0.10576536 0.97208687]
 [0.50119868 0.66378839 0.61579511 0.04466394 0.01365171 0.46678992
  0.49861541 0.46448035 0.59320483 0.21572336]
 [0.05525124 0.2555439  0.07277069 0.50208789 0.21474207 0.23508069
  0.55686817 0.65810705 0.6105268  0.10349968]
 [0.14923889 0.23898238 0.32834692 0.58015278 0.23389074 0.04261324
  0.77779498 0.42902259 0.73498553 0.19227414]
 [0.00275505 0.16485587 0.79409495 0.33991278 0.14526563 0.18569461
  0.24115268 0.58625285 0.89823973 0.04763815]
 [0.46307819 0.63535966 0.45599204 0.69696626 0.92395245 0.13878568
  0.22377856 0.47425183 0.45911011 0.56902674]
 [0.04749591 0.03246952 0.97927197 0.6321106  0.0114484  0.54483657
  0.05891254 0.94695521 0.06129333 0.85367954]
 [0.87182556 0.63652332 0.52898194 0.08532297 0.22233547 0.32425865
  0.8451314 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [111]:
np.random.random(30).mean()

np.float64(0.45213570389583974)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [134]:
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [141]:
arr = np.random.random((2, 3))
np.pad(arr, 1)

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.24392835, 0.72365601, 0.7479117 , 0.        ],
       [0.        , 0.35700972, 0.42455853, 0.06325641, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [162]:
3 * 0.09999999999999999 == 0.3

True

In [145]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [22]:
np.diag(np.array([1, 2, 3, 4]), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [29]:
z = np.ones((8, 8), dtype = int)
z[::2, ::2] = 0
z[1::2, 1::2] = 0
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [26]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [193]:
np.unravel_index(99,(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [206]:
np.tile(np.array([[1, 0], [0, 1]]), reps = (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [212]:
z = np.random.random((5, 5))
z = (z - np.mean(z))/np.std(z)
z

array([[-0.64342455, -0.2532121 , -1.39479298,  1.27460374,  0.92159954],
       [-0.5529697 ,  0.26082561, -1.6560456 ,  0.60894803,  1.34837707],
       [ 0.36834129,  1.70602781,  0.38765536,  0.55670883, -0.80655146],
       [-0.88736517,  0.4568231 , -1.42172476, -0.42414682, -1.26940487],
       [ 1.04247307,  1.65793594, -0.64906684,  0.51345871, -1.14507325]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [216]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [223]:
z1 = np.random.random((5, 3))
z2 = np.random.random((3, 2))

print(z1)
print(z2)

print(np.matmul(z1, z2))

z1 @ z2

[[0.83708302 0.27939845 0.23736887]
 [0.37657123 0.62464742 0.55722744]
 [0.5361599  0.66999009 0.3535699 ]
 [0.90875458 0.50349918 0.19041707]
 [0.79235922 0.31646423 0.93380767]]
[[0.08912321 0.83483806]
 [0.85387155 0.61976736]
 [0.02542827 0.39320356]]
[[0.31920979 0.96532509]
 [0.58109923 0.92061589]
 [0.62886044 1.00186963]
 [0.51575673 1.14558794]
 [0.36458252 1.22480234]]


array([[0.31920979, 0.96532509],
       [0.58109923, 0.92061589],
       [0.62886044, 1.00186963],
       [0.51575673, 1.14558794],
       [0.36458252, 1.22480234]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [239]:
z =  np.random.random(10) *10
z[(z > 3) & (z < 8)] *= -1
z

array([-7.35595541,  8.93289256,  1.22424254, -5.56453165, -6.73191347,
        8.08776253,  1.18005622, -3.50400648,  2.75992176, -6.0052194 ])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [245]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [260]:
T1 = np.array([[1, 2, 3], [2, 4, 6]])
T1**T1

array([[    1,     4,    27],
       [    4,   256, 46656]])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [41]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\Vipin Tiwari\AppData\Local\Temp\ipykernel_8420\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [44]:
np.round(np.random.random((3, 3, 2)), 0)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [0., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 1.],
        [1., 0.]]])

#### 30. How to find common values between two arrays? (★☆☆)

In [73]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print("Z1 = ", Z1, "\nZ2 = ", Z2)
print(np.intersect1d(Z1,Z2))

Z1 =  [4 5 4 5 8 3 6 8 1 0] 
Z2 =  [9 2 9 5 7 9 4 9 8 2]
[4 5 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [65]:
arr1 = np.random.randint(1, 20, (3, 7))

print(arr1)

arr1[1, :] = arr1[2, :]

print(arr1)

[[11  3 14 11 11  9 17]
 [ 3 17 18 13  8  2 18]
 [15  6 18 10  8 18  7]]
[[11  3 14 11 11  9 17]
 [15  6 18 10  8 18  7]
 [15  6 18 10  8 18  7]]


In [69]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,2]] = A[[2,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)